### ISSUE TITLE
"unexpected token" when building from Source (Nodejs v18)/ Ubuntu

### ISSUE THREAD

**Issue by ertemann** [initia-labs/rapid-relayer#11]
Getting errors upon start after building from Source, all relate to certain syntax errors.

ex1:

```
ibc-relayer@0.0.1 start
> node --stack_size=4096 --max-old-space-size=4096 -r ts-node/register/transpile-only -r tsconfig-paths/register src/index.ts
/home/deploy/rapid-relayer/node_modules/typescript/lib/typescript.js:139
    for (let i = startIndex ?? 0; i < array.length; i++) {
                             ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at attemptRequireWithV8CompileCache (/home/deploy/rapid-relayer/node_modules/ts-node/dist/util.js:104:16)
    at loadCompiler (/home/deploy/rapid-relayer/node_modules/ts-node/dist/configuration.js:237:56)
    at resolveAndLoadCompiler (/home/deploy/rapid-relayer/node_modules/ts-node/dist/configuration.js:226:16)
rapid-relayer.service: Main process exited, code=exited, status=1/FAILURE
rapid-relayer.service: Failed with result 'exit-code'. 
```

ex2:
```
file:///home/deploy/rapid-relayer/node_modules/husky/bin.mjs:14
 ;(o.scripts ||= {}).prepare = 'husky'
               ^

SyntaxError: Unexpected token '='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /home/deploy/rapid-relayer
npm ERR! command failed
npm ERR! command sh -c husky

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2024-09-10T20_38_59_739Z-debug-0.log
```

Config example used:

```
{
  "port": 3000,
  "logLevel": "info",
  "pairs": [
    {
      "name": "dydx-secretnetwork",
      "chainA": {
                                                                                "bech32Prefix": "dydx",
        "chainId": "dydx-mainnet-1",
        "gasPrice": "0.025ibc/8E27BA2D5493AF5636760E354E46004562C46AB7EC0CC4C1CA14E9E20E2545B5",
        "lcdUri": "https://.......",
        "rpcUri": "https://.......",
        "key": {
          "type": "mnemonic",
          "privateKey": "Bla Bla Bla"
        },
        "connectionId": "connection-5",
        "syncInfo": {
          "height": 1, 
          "txIndex": 0 
        }
              },
      "chainB": {
                                                                                "bech32Prefix": "secret",
        "chainId": "secret-4",
        "gasPrice": "0.05uscrt",
        "lcdUri": "https://.......",
        "rpcUri": "https://.......",
        "key": {
          "type": "mnemonic",
          "privateKey": "Bla Bla Bla"
        },
        "connectionId": "connection-128",
        "syncInfo": {
          "height": 1, 
          "txIndex": 0 
        }
              }
    },    {
      "name": "noble-osmosis",
      "chainA": {
                                                                                "bech32Prefix": "noble",
        "chainId": "noble-1",
        "gasPrice": "0uusdc",
        "lcdUri": "https://.......",
        "rpcUri": "https://.......",
        "key": {
          "type": "mnemonic",
          "privateKey": "Bla Bla Bla"
        },
        "connectionId": "connection-2",
        "syncInfo": {
          "height": 1, 
          "txIndex": 0 
        }
              },
      "chainB": {
                                                                                "bech32Prefix": "osmo",
        "chainId": "osmosis-1",
        "gasPrice": "0.005uosmo",
        "lcdUri": "https://.......",
        "rpcUri": "https://.......",
        "key": {
          "type": "mnemonic",
          "privateKey": "Bla Bla Bla"
        },
        "connectionId": "connection-2241",
        "syncInfo": {
          "height": 1, 
          "txIndex": 0 
        }
              }
    }  ]
}
```

**Comment by ALPAC-4** [comment]
Sorry for the late response. We just updated the rapid relayer and it works well on node version 18

```bash
rapid-relayer % node --version
v18.20.5

rapid-relayer % npm start     

> rapid-relayer@0.0.1 start
> node --stack_size=4096 --max-old-space-size=4096 -r ts-node/register/transpile-only -r tsconfig-paths/register src/index.ts

2024-12-06T06:26:01.459Z info: status app listen to port 7010
2024-12-06T06:26:01.459Z info: rapid relayer has been started
2024-12-06T06:26:01.460Z info: {
...
```

Can you check the updated? Thank you

**Comment by ertemann** [comment]
Yeah havent had issues, was able to build and run about a month ago. sorry for not closing
